Repository singh04ayush/Imagify, pull requests merged in 2025-04, with the labels that each got.

#14 #13 Fixed navbar stylings and mismatching issues
  client/package-lock.json
  client/src/components/Header.jsx
  client/src/components/Navbar.jsx
Labels: bug, enhancement, good first issue

#16 Added footer to the website
  client/src/components/Footer.jsx
Labels: enhancement, good first issue

#24 🎨 Redesign Navbar with Modern UI and Improved User Experience
  client/src/components/Navbar.jsx
Labels: good first issue, UI enhancement

#28 scroll to the top when navigating to result page
  client/src/pages/Result.jsx
Labels: bug, good first issue

#35 Fix: Implemented User Dashboard and Environment Setup (#33)
  .gitignore
  client/package-lock.json
  client/src/App.jsx
  client/src/components/Login.jsx
  client/src/context/AppContext.jsx
  client/src/pages/Dashboard.jsx
  server/config/mongodb.js
  server/controllers/imageControllers.js
  server/middlewares/auth.js
  server/models/imageModel.js
  server/routes/imageRoutes.js
Labels: enhancement, good first issue, UI enhancement, feature

#45 Fixed : 🎨 Enhance Navbar Responsiveness and Mobile Experience (#38)
  README.md
  client/package-lock.json
  client/src/components/Footer.jsx
  client/src/components/Navbar.jsx
Labels: bug, enhancement, good first issue, UI enhancement, feature
